[package]
name = "crufty"
version = "0.0.1"
authors = ["Felix Rath <felixr@archlinux.info>"]

[dependencies.glium]
version = "0.14.0"
# features = ["glutin", "image", "nalgebra"]

[dependencies]
image = "0.10.0"
ecs = "0.23.0"
nalgebra = "0.8.1"
hprof = "0.1.3"
clock_ticks = "0.1.0"
ncollide = "0.8.0"
num = "0.1.31"
ordered-float = "0.2.1"
toml = "0.1.28"
mio = "0.6.1"
byteorder = "0.5.3"
newtype_derive = "0.1.6"
custom_derive = "0.1.5"
rand = "0.3.14"
smallvec = "0.2.1"
