[package]
name = "crufty"
version = "0.0.1"
authors = ["Felix Rath <felixr@archlinux.info>"]

[dependencies.glium]
version = "0.13"
# features = ["glutin", "image", "nalgebra"]

[dependencies]
image = "*"
ecs = "0.22"
nalgebra = "*"
hprof = "*"
clock_ticks = "*"
ncollide = "*"
num = "*"
