[package]
name = "crufty"
version = "0.0.1"
authors = ["Felix Rath <felixr@archlinux.info>"]

[dependencies.glium]
version = "*"
features = ["image", "nalgebra"]

[dependencies]
glutin = "*"
ecs = "*"