[package]
name = "crufty"
version = "0.0.1"
authors = ["Felix Rath <felixr@archlinux.info>"]

[dependencies]
glium = "*"
image = "*"
ecs = "*"
nalgebra = "*"
hprof = "*"
clock_ticks = "*"
ncollide = "*"
