[package]
name = "crufty"
version = "0.0.1"
authors = ["Felix Rath <felixr@archlinux.info>"]

[dependencies.glium]
version = "0.8.0"
features = ["glutin", "image", "nalgebra"]

[dependencies]
image = "*"
ecs = "*"
nalgebra = "*"
hprof = "*"
clock_ticks = "*"
ncollide = "*"
